# Site settings
title: MEAN.JS
email: support@meanjs.org
description: > # Full-Stack JavaScript Using MongoDB, Express, AngularJS, and Node.js
baseurl: "" # For the Live MEAN WEBSITE
url: "http://meanjs.org/" # FOR THE LIVE MEAN WEBSITE
twitter_username: Meanjsorg
github_username:  meanjs

# Build settings
markdown: kramdown

excludes: 
  - node_modules
